{
 "title": "PostgreSQL Exporter",
 "description": "postgres exporter Dashboard for display important postgreSQL metric",
 "tags": [ "PG" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values({job=\"postgres\"},instance)"
    }
   },
   {
    "name": "Database",
    "query": {
     "query": "label_values(pg_database_connection_limit{datname=\"blockchain_db\"},datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_server_version_num{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Replication Lag",
   "type": "stat",
   "description": "Max Replication lag behind master in seconds\n\nOnly available on a standby system.\n\nSource: pg_last_xact_replay_timestamp\n\nUse: pg_stat_replication for Details.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_lag_seconds{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "stat",
   "description": "Clients executing Statements.\n\nSource: pg_stat_activity",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})/(sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})+sum(pg_stat_database_blks_read{instance=~\"$Instance\"}))*100"
    }
   ]
  },
  {
   "title": "Connections used",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)/max(pg_settings_max_connections)"
    }
   ]
  },
  {
   "title": "Commit Ratio",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{instance=\"$Instance\"})/(sum(pg_stat_database_xact_commit{instance=\"$Instance\"}) + sum(pg_stat_database_xact_rollback{instance=\"$Instance\"}))"
    }
   ]
  },
  {
   "title": "Total database size",
   "type": "stat",
   "description": "Size of all databases in $Instance.\n\nSource: pg_database_size()",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{instance=\"$Instance\"}) / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{datname=\"blockchain_db\"}[5m])))+sum((rate(pg_stat_database_xact_rollback{datname=\"blockchain_db\"}[5m])))"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "description": "Setting: max_connections in postgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_max_connections{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PostgreSQL Uptime",
   "type": "timeseries",
   "description": "Source: pg_postmaster_start_time()",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - pg_postmaster_start_time{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Tuples inserts/updates/deletes",
   "type": "timeseries",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_inserted{instance=\"$Instance\"}[1h])))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_updated{instance=\"$Instance\"}[1h])))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_deleted{instance=\"$Instance\"}[1h])))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_xact_commit[1h])))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum ((rate(pg_stat_database_xact_rollback[1h])))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Tuples fetched/returned",
   "type": "timeseries",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_fetched{instance=\"$Instance\"}[1h])))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_returned{instance=\"$Instance\"}[1h])))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "I/O Read/Write time",
   "type": "timeseries",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_blk_read_time{instance=\"$Instance\"}[1h])))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum ((rate(pg_stat_database_blk_write_time{instance=\"$Instance\"}[1h])))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "timeseries",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{instance=\"$Instance\"}[1h]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temporary files by database",
   "type": "timeseries",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_temp_files{instance=\"$Instance\"}[1h]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Locks by state",
   "type": "timeseries",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{instance=\"$Instance\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}