{
 "title": "Common network activity",
 "description": "Common network activity",
 "tags": [ "ETH" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average time btw blocks",
   "type": "stat",
   "description": "Average time between blocks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH time_diffs AS (\r\n    SELECT\r\n        EXTRACT(EPOCH FROM (timestamp - LAG(timestamp) OVER (ORDER BY \"blockNumber\"))) AS block_time_diff\r\n    FROM eth_transactions\r\n)\r\nSELECT AVG(block_time_diff) AS avg_block_time\r\nFROM time_diffs\r\nWHERE block_time_diff IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Transactions amount per block",
   "type": "table",
   "description": "Transactions amount per block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"blockNumber\", COUNT(*) as tx_count FROM eth_transactions GROUP BY \"blockNumber\" ORDER BY \"blockNumber\" desc;"
    }
   ]
  },
  {
   "title": "Top 5 senders",
   "type": "bargauge",
   "description": "Top 5 senders",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"from\", COUNT(*) as tx_count FROM eth_transactions GROUP BY \"from\" ORDER BY tx_count DESC LIMIT 5;"
    }
   ]
  }
 ]
}