{
 "title": "Gas and transactions price analysis",
 "description": "Gas and transactions price analysis",
 "tags": [ "ETH" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Тotal Gas Used",
   "type": "barchart",
   "description": "Тotal Gas Used",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('hour', timestamp) as time, SUM(gas * \"gasPrice\") / 10^18 as \"total_gas_cost (ETH)\" FROM eth_transactions GROUP BY time;"
    }
   ]
  },
  {
   "title": "AVG maxFeePerGas and maxPriorityFeePerGas",
   "type": "timeseries",
   "description": "Transactions type 2 average maxFeePerGas and maxPriorityFeePerGas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', timestamp) as time, AVG(\"maxFeePerGas\") as \"AVG maxFeePerGas\", AVG(\"maxPriorityFeePerGas\") as \"AVG maxPriorityFeePerGas\" FROM eth_transactions WHERE type = 2 GROUP BY time;"
    }
   ]
  },
  {
   "title": "AVG gasPrice",
   "type": "timeseries",
   "description": "Average gas price by time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', timestamp) as time, AVG(\"gasPrice\") as avg_gas_price FROM eth_transactions WHERE type = 0 GROUP BY time ORDER BY time;"
    }
   ]
  }
 ]
}