{
 "title": "User behavior and smart-contacts analysis",
 "description": "User behavior and smart-contacts analysis",
 "tags": [ "ETH" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Input using frequency",
   "type": "timeseries",
   "description": "Input using frequency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', timestamp) as time, COUNT(*) FILTER (WHERE input != '') as contract_calls FROM eth_transactions GROUP BY time;"
    }
   ]
  },
  {
   "title": "AVG value by trx type",
   "type": "stat",
   "description": "Average value by transactions type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT type, AVG(value) / 10^18 as \"AVG value (ETH)\" FROM eth_transactions GROUP BY type order by type;"
    }
   ]
  },
  {
   "title": "Top 10 receipients",
   "type": "table",
   "description": "Top 10 recipients",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"to\", COUNT(*) as tx_count, SUM(value) as total_value FROM eth_transactions GROUP BY \"to\" ORDER BY total_value DESC LIMIT 10;"
    }
   ]
  }
 ]
}