apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
    editable: true
  
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    uid: clickhouse
    user: default
    secureJsonData:
      password: ""
    jsonData:
      defaultDatabase: blockchain_db
      server: clickhouse
      port: 9000
      username: default
      tlsSkipVerify: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres_prod:5432
    uid: postgres
    user: user
    secureJsonData:
      password: 'password'
    jsonData:
      database: blockchain_db
      sslmode: 'disable'
    editable: true
